language: emacs-lisp

cache:
  - directories:
      # Cache stable Emacs binaries (saves 1 min per job)
      - "$HOME/emacs/"

env:
  - "TARGET=check             LISP=sbcl  EMACS_VERSION=24.4"
  - "TARGET=check-fancy       LISP=sbcl  EMACS_VERSION=24.4"
  - "TARGET=check             LISP=sbcl  EMACS_VERSION=25.2"
  - "TARGET=check-fancy       LISP=sbcl  EMACS_VERSION=25.2"
  - "TARGET=check             LISP=sbcl  EMACS_VERSION=26.1"
  - "TARGET=check-fancy       LISP=sbcl  EMACS_VERSION=26.1"
  - "TARGET=check             LISP=ccl   EMACS_VERSION=26.1"
  - "TARGET=check-fancy       LISP=ccl   EMACS_VERSION=26.1"  
  - "TARGET=check-repl        LISP=sbcl  EMACS_VERSION=26.1"
  - "TARGET=check-indentation LISP=sbcl  EMACS_VERSION=26.1"
  #- "TARGET=check-fancy      LISP=cmucl EMACS_VERSION=26.1"
  #- "TARGET=check            LISP=cmucl EMACS_VERSION=26.1"

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs

script:
  - make LISP=$LISP EMACS=$HOME/emacs/$EMACS_VERSION/src/emacs $TARGET
